language: scala
sudo: required
scala:
  - 2.12.0
  - 2.12.1
  - 2.12.2

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

os:
  - linux
  - osx

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M -J-Xms1024M test