language: scala
sudo: required
scala:
  - 2.12.0
  - 2.12.1
  - 2.12.2

os:
  - linux
  - osx

jdk: oraclejdk8
osx_image: xcode8

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M -J-Xms1024M test