language: scala
scala:
  - 2.10.4
  - 2.11.8
  - 2.12.0
  - 2.12.1
jdk:
  - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M -J-Xms1024M test

